import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import path from 'node:path';
const execFileAsync=promisify(execFile);
async function run(cmd,args,timeout=30000){const {stdout='',stderr=''}=await execFileAsync(cmd,args,{timeout,maxBuffer:8*1024*1024,encoding:'utf8'});return`${stdout}\n${stderr}`.trim()}
const near=(a,b,tol=0.8)=>Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)<=tol;
function dimensionCheck(actualW,actualH,expected){if(!expected?.widthMm||!expected?.heightMm)return{status:'manual',message:'Gabarito sem dimensoes estruturadas.'};const bleed=Number(expected.bleedMm||0);const candidates=[[Number(expected.widthMm),Number(expected.heightMm)],[Number(expected.widthMm)+2*bleed,Number(expected.heightMm)+2*bleed]];const ok=candidates.some(([w,h])=>near(actualW,w)&&near(actualH,h));return{status:ok?'pass':'fail',message:ok?'Dimensoes compativeis com o gabarito.':`Arquivo ${actualW.toFixed(2)}x${actualH.toFixed(2)} mm; esperado ${expected.widthMm}x${expected.heightMm} mm${bleed?` (sangria ${bleed} mm)`:''}.`,actual:{widthMm:actualW,heightMm:actualH},expected};}
function pageCheck(pages,side,supportsBack){if(side==='duplex')return{status:pages===2?'pass':'fail',message:`Duplex: ${pages} pagina(s); esperado 2.`};if(side==='front'||side==='back')return{status:pages===1?'pass':'fail',message:`Face unica: ${pages} pagina(s); esperado 1.`};if(supportsBack)return{status:pages>=1&&pages<=2?'pass':'warning',message:`Arquivo geral com ${pages} pagina(s); produto admite frente/verso.`};return{status:pages===1?'pass':'warning',message:`Arquivo geral com ${pages} pagina(s).`};}
function finalState(checks){if(checks.some(c=>c.status==='fail'))return'fail';if(checks.some(c=>c.status==='manual'))return'manual';if(checks.some(c=>c.status==='warning'))return'warning';return'pass';}
export async function analyzePdf(file,{side='general',supportsBack=false,expected,minDpi=200}={}){const info=await run('pdfinfo',['-box',file]);const pages=Number(info.match(/^Pages:\s+(\d+)/m)?.[1]||0);const size=info.match(/^Page size:\s+([\d.]+)\s+x\s+([\d.]+)\s+pts/m)||info.match(/^Page\s+1\s+size:\s+([\d.]+)\s+x\s+([\d.]+)\s+pts/m);const widthMm=size?Number(size[1])*25.4/72:NaN;const heightMm=size?Number(size[2])*25.4/72:NaN;const imageList=await run('pdfimages',['-list',file]);const embedded=[];for(const line of imageList.split(/\r?\n/)){const t=line.trim().split(/\s+/);if(t.length>=15&&/^\d+$/.test(t[0])&&/^\d+$/.test(t[1])){const xPpi=Number(t[12]),yPpi=Number(t[13]);embedded.push({page:Number(t[0]),type:t[2],width:Number(t[3]),height:Number(t[4]),color:t[5],xPpi:Number.isFinite(xPpi)?xPpi:null,yPpi:Number.isFinite(yPpi)?yPpi:null});}}
 let ink=[];try{const out=await run('gs',['-q','-o','-','-sDEVICE=inkcov',file],60000);for(const line of out.split(/\r?\n/)){const m=line.match(/^\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+CMYK/);if(m)ink.push({c:Number(m[1]),m:Number(m[2]),y:Number(m[3]),k:Number(m[4])});}}catch{}
 const ppis=embedded.flatMap(i=>[i.xPpi,i.yPpi]).filter(Number.isFinite);const minFoundPpi=ppis.length?Math.min(...ppis):null;const checks=[pageCheck(pages,side,supportsBack),dimensionCheck(widthMm,heightMm,expected)];if(minFoundPpi==null)checks.push({status:'pass',message:'Nenhuma imagem raster embutida detectada; DPI nao limita elementos vetoriais.'});else checks.push({status:minFoundPpi>=minDpi?'pass':'fail',message:`Menor resolucao raster: ${minFoundPpi} PPI; minimo ${minDpi} PPI.`,minFoundPpi,minDpi});const spaces=[...new Set(embedded.map(i=>i.color).filter(Boolean))];checks.push({status:'pass',message:`Espacos de cor raster detectados: ${spaces.join(', ')||'nenhum raster'}.`,spaces,inkCoverage:ink});return{engine:'poppler+ghostscript',type:'pdf',pages,widthMm:Number.isFinite(widthMm)?Number(widthMm.toFixed(3)):null,heightMm:Number.isFinite(heightMm)?Number(heightMm.toFixed(3)):null,embeddedImages:embedded,inkCoverage:ink,checks,state:finalState(checks)};}
export async function analyzeRaster(file,{expected,minDpi=200}={}){const out=await run('identify',['-format','%w|%h|%x|%y|%U|%[colorspace]',file]);const [w,h,xr,yr,unit,colorSpace]=out.split('|');const widthPx=Number(w),heightPx=Number(h),xRes=Number.parseFloat(xr),yRes=Number.parseFloat(yr);let dpiX=null,dpiY=null;if(unit==='PixelsPerInch'){dpiX=xRes;dpiY=yRes}else if(unit==='PixelsPerCentimeter'){dpiX=xRes*2.54;dpiY=yRes*2.54}const widthMm=dpiX?widthPx/dpiX*25.4:null,heightMm=dpiY?heightPx/dpiY*25.4:null;const checks=[];if(dpiX&&dpiY){const minFound=Math.min(dpiX,dpiY);checks.push({status:minFound>=minDpi?'pass':'fail',message:`Resolucao ${Math.round(dpiX)}x${Math.round(dpiY)} PPI; minimo ${minDpi} PPI.`});checks.push(dimensionCheck(widthMm,heightMm,expected));}else checks.push({status:'manual',message:'Imagem raster sem densidade fisica confiavel; dimensao de impressao exige revisao manual.'});checks.push({status:/CMYK/i.test(colorSpace)?'pass':'warning',message:`Espaco de cor informado pelo arquivo: ${colorSpace||'desconhecido'}.`});return{engine:'imagemagick',type:'raster',widthPx,heightPx,dpiX,dpiY,widthMm,heightMm,colorSpace,checks,state:finalState(checks)};}
export async function analyzeArtwork(file,options={}){const mime=String(options.mimeType||'').toLowerCase();const ext=path.extname(file).toLowerCase();if(mime==='application/pdf'||ext==='.pdf')return analyzePdf(file,options);if(mime.startsWith('image/')&&mime!=='image/svg+xml'||['.png','.jpg','.jpeg','.tif','.tiff'].includes(ext))return analyzeRaster(file,options);return{engine:'manual',type:mime||ext||'unknown',checks:[{status:'manual',message:'Formato preservado, mas exige conferencia manual ou conversao controlada antes da producao.'}],state:'manual'};}
