import crypto from 'node:crypto';
import path from 'node:path';
import { z } from 'zod';
import { getDb } from '../lib/db.js';
import { deleteObject, headObject, R2_PREFIXES, r2Status, signedUploadUrl } from '../lib/storage.js';

const intentSchema=z.object({filename:z.string().min(1).max(255),contentType:z.string().min(3).max(120),side:z.enum(['front','back','duplex','general']).default('general')});
const confirmSchema=z.object({key:z.string().min(10).max(500),filename:z.string().min(1).max(255),side:z.enum(['front','back','duplex','general']).default('general'),checksumSha256:z.string().regex(/^[a-fA-F0-9]{64}$/).optional().nullable()});
const allowedTypes=new Set(['application/pdf','image/png','image/jpeg','image/svg+xml','application/postscript','application/eps','application/octet-stream']);
const tokenHash=token=>crypto.createHash('sha256').update(String(token)).digest('hex');
function safeExt(name){const ext=path.extname(name).toLowerCase().replace(/[^a-z0-9.]/g,'');return ext.length<=12?ext:''}
async function context(db,number,itemId,token){if(!token)return null;const [rows]=await db.execute(`SELECT o.id AS order_id,o.order_number,oi.id AS item_id,p.requires_artwork,p.supports_front,p.supports_back FROM orders o JOIN order_access_tokens oat ON oat.order_id=o.id JOIN order_items oi ON oi.order_id=o.id LEFT JOIN products p ON p.id=oi.product_id WHERE o.order_number=? AND oi.id=? AND oat.token_hash=? AND oat.revoked_at IS NULL AND oat.expires_at>NOW() LIMIT 1`,[number,itemId,tokenHash(token)]);return rows[0]||null}
function sideAllowed(ctx,side){if(!ctx.requires_artwork)return false;if(side==='back')return Boolean(ctx.supports_back);if(side==='front')return Boolean(ctx.supports_front);if(side==='duplex')return Boolean(ctx.supports_front&&ctx.supports_back);return true}
export async function registerArtworkRoutes(app){
 app.post('/api/v1/orders/:number/items/:itemId/artwork/upload-intent',{config:{rateLimit:{max:30,timeWindow:'1 hour'}}},async(request,reply)=>{const parsed=intentSchema.safeParse(request.body);if(!parsed.success||!allowedTypes.has(parsed.data?.contentType))return reply.code(400).send({error:'INVALID_ARTWORK'});if(await r2Status()!=='ok')return reply.code(503).send({error:'R2_NOT_READY'});const db=getDb();const token=String(request.headers['x-order-token']||'').trim();const ctx=await context(db,String(request.params.number),Number(request.params.itemId),token);if(!ctx)return reply.code(404).send({error:'ORDER_ITEM_NOT_FOUND'});if(!sideAllowed(ctx,parsed.data.side))return reply.code(409).send({error:'ARTWORK_SIDE_NOT_SUPPORTED'});const prefix=`${R2_PREFIXES.ARTWORK_ORIGINALS}/order-${ctx.order_id}/item-${ctx.item_id}`;const key=`${prefix}/${crypto.randomUUID()}${safeExt(parsed.data.filename)}`;const uploadUrl=await signedUploadUrl({key,contentType:parsed.data.contentType,expiresIn:900,metadata:{'cp-order':String(ctx.order_id),'cp-item':String(ctx.item_id),'cp-side':parsed.data.side}});return{key,uploadUrl,expiresIn:900,maxBytes:104857600,visibility:'private'};});
 app.post('/api/v1/orders/:number/items/:itemId/artwork/confirm',async(request,reply)=>{const parsed=confirmSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_ARTWORK_CONFIRMATION'});const db=getDb();const token=String(request.headers['x-order-token']||'').trim();const ctx=await context(db,String(request.params.number),Number(request.params.itemId),token);if(!ctx)return reply.code(404).send({error:'ORDER_ITEM_NOT_FOUND'});if(!sideAllowed(ctx,parsed.data.side))return reply.code(409).send({error:'ARTWORK_SIDE_NOT_SUPPORTED'});const expected=`${R2_PREFIXES.ARTWORK_ORIGINALS}/order-${ctx.order_id}/item-${ctx.item_id}/`;if(!parsed.data.key.startsWith(expected))return reply.code(403).send({error:'ARTWORK_KEY_MISMATCH'});let remote;try{remote=await headObject(parsed.data.key)}catch{return reply.code(409).send({error:'R2_OBJECT_NOT_FOUND'})}if(remote.size<=0||remote.size>104857600){try{await deleteObject(parsed.data.key)}catch{}return reply.code(413).send({error:'ARTWORK_SIZE_INVALID',maxBytes:104857600})}if(!allowedTypes.has(remote.contentType||''))return reply.code(415).send({error:'ARTWORK_TYPE_INVALID'});const connection=await db.getConnection();try{await connection.beginTransaction();const [mr]=await connection.execute(`INSERT INTO media_objects (kind,visibility,storage_provider,bucket_name,object_key,original_name,mime_type,size_bytes,checksum_sha256,metadata_json) VALUES ('artwork-original','private','cloudflare-r2',?,?,?,?,?,?,?)`,[process.env.R2_BUCKET,parsed.data.key,parsed.data.filename,remote.contentType,remote.size,parsed.data.checksumSha256||null,JSON.stringify({etag:remote.etag,r2:remote.metadata})]);const [ar]=await connection.execute(`INSERT INTO artworks (order_item_id,original_media_id,side,status,preflight_json) VALUES (?,?,?,'uploaded',?)`,[ctx.item_id,mr.insertId,parsed.data.side,JSON.stringify({status:'pending',sourceType:remote.contentType})]);await connection.execute(`INSERT INTO artwork_events (artwork_id,event_type,actor_type,payload_json) VALUES (?,'artwork.uploaded','customer',?)`,[ar.insertId,JSON.stringify({filename:parsed.data.filename,size:remote.size,contentType:remote.contentType})]);await connection.execute(`INSERT INTO order_events (order_id,event_type,actor_type,payload_json) VALUES (?,'artwork.uploaded','customer',?)`,[ctx.order_id,JSON.stringify({itemId:ctx.item_id,artworkId:ar.insertId,side:parsed.data.side})]);await connection.commit();return reply.code(201).send({ok:true,artworkId:Number(ar.insertId),status:'uploaded',preflight:'pending'})}catch(error){try{await connection.rollback()}catch{}throw error}finally{connection.release()}});
}