CREATE TABLE IF NOT EXISTS external_reference_assets (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  provider ENUM('google_drive','web','manual') NOT NULL DEFAULT 'manual',
  external_id VARCHAR(255) NOT NULL,
  external_url VARCHAR(1200) NOT NULL,
  source_type ENUM('folder','file') NOT NULL,
  source_group VARCHAR(190) NULL,
  title VARCHAR(500) NOT NULL,
  mime_type VARCHAR(190) NULL,
  supplier_hint VARCHAR(190) NULL,
  usage_hint ENUM('product','hero','template','reference','unknown') NOT NULL DEFAULT 'reference',
  photo_type_hint ENUM('real','render','illustration','not_applicable','unknown') NOT NULL DEFAULT 'unknown',
  supplier_branding_risk ENUM('clear','found','unknown') NOT NULL DEFAULT 'unknown',
  price_text_risk ENUM('clear','found','unknown') NOT NULL DEFAULT 'unknown',
  license_status ENUM('owned','licensed','reference_only','unknown') NOT NULL DEFAULT 'reference_only',
  ingestion_status ENUM('discovered','quarantined','reviewed','imported','rejected') NOT NULL DEFAULT 'quarantined',
  review_required TINYINT(1) NOT NULL DEFAULT 1,
  metadata_json JSON NULL,
  discovered_at DATETIME NULL,
  reviewed_at DATETIME NULL,
  imported_media_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_external_reference_provider_id (provider,external_id),
  KEY idx_external_reference_status (ingestion_status,usage_hint),
  KEY idx_external_reference_risk (supplier_branding_risk,price_text_risk),
  CONSTRAINT fk_external_reference_imported_media FOREIGN KEY (imported_media_id) REFERENCES media_objects(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
