CREATE TABLE IF NOT EXISTS supplier_price_imports (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  supplier_id BIGINT UNSIGNED NULL,
  source_name VARCHAR(255) NOT NULL,
  source_filename VARCHAR(500) NOT NULL,
  source_checksum_sha256 CHAR(64) NOT NULL,
  source_date DATE NULL,
  source_format ENUM('html_xls','csv','xlsx','manual') NOT NULL DEFAULT 'html_xls',
  status ENUM('staged','reviewed','applied','rejected') NOT NULL DEFAULT 'staged',
  row_count INT UNSIGNED NOT NULL DEFAULT 0,
  category_count INT UNSIGNED NOT NULL DEFAULT 0,
  matched_count INT UNSIGNED NOT NULL DEFAULT 0,
  conflict_count INT UNSIGNED NOT NULL DEFAULT 0,
  metadata_json JSON NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  reviewed_by_user_id BIGINT UNSIGNED NULL,
  reviewed_at DATETIME NULL,
  applied_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_supplier_price_import_checksum (source_checksum_sha256),
  KEY idx_supplier_price_import_status (status,created_at),
  KEY idx_supplier_price_import_supplier (supplier_id,source_date),
  CONSTRAINT fk_supplier_price_import_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL,
  CONSTRAINT fk_supplier_price_import_creator FOREIGN KEY (created_by_user_id) REFERENCES staff_users(id) ON DELETE SET NULL,
  CONSTRAINT fk_supplier_price_import_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES staff_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_price_rows (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  import_id BIGINT UNSIGNED NOT NULL,
  source_row_number INT UNSIGNED NOT NULL,
  source_code VARCHAR(190) NOT NULL,
  category_name VARCHAR(255) NOT NULL,
  service_description TEXT NOT NULL,
  color_configuration VARCHAR(80) NULL,
  weight_value DECIMAL(14,3) NULL,
  quantity_value DECIMAL(14,3) NULL,
  size_label VARCHAR(190) NULL,
  production_days INT UNSIGNED NULL,
  supplier_price DECIMAL(14,2) NOT NULL,
  matched_variant_id BIGINT UNSIGNED NULL,
  match_status ENUM('unmatched','exact','conflict','manual') NOT NULL DEFAULT 'unmatched',
  review_status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  raw_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_supplier_price_import_row (import_id,source_row_number),
  UNIQUE KEY uq_supplier_price_import_code (import_id,source_code),
  KEY idx_supplier_price_row_match (import_id,match_status),
  KEY idx_supplier_price_row_review (import_id,review_status),
  KEY idx_supplier_price_row_category (import_id,category_name),
  KEY idx_supplier_price_row_variant (matched_variant_id),
  CONSTRAINT fk_supplier_price_row_import FOREIGN KEY (import_id) REFERENCES supplier_price_imports(id) ON DELETE CASCADE,
  CONSTRAINT fk_supplier_price_row_variant FOREIGN KEY (matched_variant_id) REFERENCES product_variants(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
